name: Android CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Install Android NDK
        run: |
          mkdir -p $ANDROID_HOME/ndk
          wget https://dl.google.com/android/repository/android-ndk-r23b-linux.zip
          unzip android-ndk-r23b-linux.zip -d $ANDROID_HOME/ndk
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/android-ndk-r23b" >> $GITHUB_ENV

      - name: Set up ANDROID_NDK_HOME
        run: echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/android-ndk-r23b" >> $GITHUB_ENV

      - name: Initialize Go Module
        run: |
          if [ ! -f go.mod ]; then
            go mod init github.com/vmanoilov/s3scanner-android
          fi
          go get golang.org/x/mobile/bind

      - name: Install Gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init

      - name: Generate Go Bindings
        run: |
          cd mobile/scanner
          gomobile bind -target=android -o scanner.aar .
          mkdir -p ../../app/libs
          cp scanner.aar ../../app/libs/

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug](#)

